# Google App Engine configuration (alternative to Cloud Run)

runtime: python311

instance_class: F4_1G

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 10

env_variables:
  PYTHONUNBUFFERED: "1"

entrypoint: gunicorn -b :$PORT flask_app:app --workers 1 --threads 8 --timeout 0

handlers:
  - url: /static
    static_dir: static
    secure: always
  
  - url: /.*
    script: auto
    secure: always

